services:

  postgres2:
    image: postgres:latest
    container_name: postgres2
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: hamidjon4424
      POSTGRES_DB: restaurant
      PG_DATA: /var/lib/postgresql/data 
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - restaurant

  migrate:
    image: migrate/migrate
    networks:
      - restaurant
    volumes:
      - ./migrations:/migrations
    command: ["-path", "/migrations", "-database", "postgres://postgres2:hamidjon4424@postgres:5432/restaurant?sslmode=disable", "up"]
    depends_on:
      - postgres2

  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6380:6379"
    volumes:
      - redis-data:/data
    networks:
      - restaurant



  reservation-service:
    build: .
    container_name: reservation-service
    ports:
      - "6666:6666"
    depends_on:
      - postgres2
      - redis
    networks:
      - restaurant

volumes:
  postgres-data:
  redis-data:

networks:
  restaurant:
    external: true